import { execFile } from "node:child_process";
import { constants } from "node:fs";
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import type { NginxConfig } from "./config.js";

const exec = promisify(execFile);

export interface NginxServer extends NginxConfig {
  hostname: string;
}

function proxyBlock(server: NginxServer): string {
  const lines = [
    "    location / {",
    ...(server.cors
      ? [
          "        add_header Access-Control-Allow-Origin *;",
          "        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';",
          "        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';",
        ]
      : []),
    `        proxy_pass http://${server.target};`,
    "        proxy_http_version 1.1;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    ...(server.websocket
      ? [
          "        proxy_set_header Upgrade $http_upgrade;",
          '        proxy_set_header Connection "upgrade";',
        ]
      : ['        proxy_set_header Connection "";']),
    ...(server.proxy_read_timeout
      ? [`        proxy_read_timeout ${server.proxy_read_timeout};`]
      : []),
    ...(server.proxy_send_timeout
      ? [`        proxy_send_timeout ${server.proxy_send_timeout};`]
      : []),
    ...(server.proxy_connect_timeout
      ? [`        proxy_connect_timeout ${server.proxy_connect_timeout};`]
      : []),
    "    }",
  ];
  return lines.join("\n");
}

function wellKnown(root?: string): string {
  return root
    ? `\n    location ^~ /.well-known/ {\n        allow all;\n        root ${root};\n    }\n`
    : "\n";
}

export function renderNginx(server: NginxServer): string {
  const httpBody = server.tls?.redirect_http
    ? "    location / {\n        return 301 https://$host$request_uri;\n    }"
    : proxyBlock(server);
  const http = `server {\n    listen 80;\n    server_name ${server.hostname};\n${wellKnown(server.well_known_root)}${httpBody}\n}`;
  if (!server.tls)
    return `# GENERATED BY cf-reconciler. DO NOT EDIT.\n\n${http}\n`;
  const https = `server {\n    listen 443 ssl;\n    server_name ${server.hostname};\n\n    ssl_certificate ${server.tls.certificate};\n    ssl_certificate_key ${server.tls.certificate_key};\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_ciphers HIGH:!aNULL:!MD5;\n    ssl_prefer_server_ciphers on;\n    ssl_session_cache shared:SSL:10m;\n    ssl_session_timeout 10m;\n${wellKnown(server.well_known_root)}${proxyBlock(server)}\n}`;
  return `# GENERATED BY cf-reconciler. DO NOT EDIT.\n\n${http}\n\n${https}\n`;
}

export interface NginxRunner {
  testCandidate(directory: string, signal?: AbortSignal): Promise<void>;
  testProduction(signal?: AbortSignal): Promise<void>;
  reload(signal?: AbortSignal): Promise<void>;
}

export class CommandNginxRunner implements NginxRunner {
  async testCandidate(directory: string, signal?: AbortSignal): Promise<void> {
    const file = join(
      dirname(directory),
      `.candidate-${process.pid}-${Date.now()}.conf`,
    );
    const hasConfigs = (await readdir(directory)).some((name) =>
      name.endsWith(".conf"),
    );
    const include = hasConfigs ? ` include ${directory}/*.conf;` : "";
    await writeFile(file, `events {}\nhttp {${include} }\n`, { mode: 0o600 });
    try {
      await exec("nginx", ["-t", "-c", file], { signal });
    } catch (error) {
      throw commandError("candidate nginx -t", error);
    } finally {
      await rm(file, { force: true });
    }
  }
  async testProduction(signal?: AbortSignal): Promise<void> {
    try {
      await exec("nginx", ["-t"], { signal });
    } catch (error) {
      throw commandError("production nginx -t", error);
    }
  }
  async reload(signal?: AbortSignal): Promise<void> {
    try {
      await exec("nginx", ["-s", "reload"], { signal });
    } catch (error) {
      throw commandError("nginx reload", error);
    }
  }
}

function commandError(operation: string, error: unknown): Error {
  const detail =
    error && typeof error === "object" && "stderr" in error
      ? String(error.stderr).trim()
      : String(error);
  return new Error(`${operation} failed: ${detail}`);
}

export interface NginxDiff {
  create: string[];
  update: string[];
  remove: string[];
}
const managedPrefix = "";

export function managedFilename(hostname: string): string {
  return `${managedPrefix}${hostname}.conf`;
}

function isManagedFilename(name: string): boolean {
  return name.startsWith(managedPrefix) && name.endsWith(".conf");
}

export const changed = (diff: NginxDiff): boolean =>
  diff.create.length + diff.update.length + diff.remove.length > 0;

export async function compareNginx(
  current: string,
  desired: ReadonlyMap<string, string>,
): Promise<NginxDiff> {
  const diff: NginxDiff = { create: [], update: [], remove: [] };
  let names: string[] = [];
  try {
    names = (await readdir(current)).filter(isManagedFilename);
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT"))
      throw error;
  }
  const existing = new Set(names);
  for (const name of names) {
    const expected = desired.get(name);
    if (expected === undefined) diff.remove.push(name);
    else if ((await readFile(join(current, name), "utf8")) !== expected)
      diff.update.push(name);
  }
  for (const name of desired.keys())
    if (!existing.has(name)) diff.create.push(name);
  diff.create.sort();
  diff.update.sort();
  diff.remove.sort();
  return diff;
}

export class NginxManager {
  constructor(private readonly runner: NginxRunner) {}

  async reconcile(
    current: string,
    desired: ReadonlyMap<string, string>,
    dryRun: boolean,
    signal?: AbortSignal,
  ): Promise<NginxDiff> {
    const workspace = dirname(current);
    if (!dryRun) await this.recover(workspace, current);
    const diff = await compareNginx(current, desired);
    if (dryRun || !changed(diff)) return diff;

    await mkdir(current, { recursive: true, mode: 0o755 });
    const staging = await mkdtemp(join(workspace, ".cf-reconciler-staging-"));
    const previous = join(workspace, ".cf-reconciler-previous");
    try {
      await Promise.all(
        [...desired].map(([name, content]) =>
          writeFile(join(staging, name), content, { mode: 0o644 }),
        ),
      );
      await this.runner.testCandidate(staging, signal);
      await rm(previous, { recursive: true, force: true });
      await mkdir(previous, { recursive: true, mode: 0o700 });
      for (const name of await this.managedNames(current))
        await rename(join(current, name), join(previous, name));
      try {
        for (const name of await readdir(staging))
          await rename(join(staging, name), join(current, name));
        await this.runner.testProduction(signal);
        await this.runner.reload(signal);
      } catch (error) {
        await this.restore(previous, current);
        throw error;
      }
      await rm(previous, { recursive: true, force: true });
      return diff;
    } finally {
      await rm(staging, { recursive: true, force: true });
    }
  }

  private async recover(workspace: string, current: string): Promise<void> {
    await mkdir(workspace, { recursive: true, mode: 0o755 });
    await mkdir(current, { recursive: true, mode: 0o755 });
    const previous = join(workspace, ".cf-reconciler-previous");
    if (await exists(previous)) await this.restore(previous, current);
    for (const name of await readdir(workspace)) {
      if (name.startsWith(".cf-reconciler-staging-"))
        await rm(join(workspace, name), { recursive: true, force: true });
    }
  }

  private async managedNames(directory: string): Promise<string[]> {
    return (await readdir(directory)).filter(isManagedFilename);
  }

  private async restore(previous: string, current: string): Promise<void> {
    for (const name of await this.managedNames(current))
      await rm(join(current, name), { force: true });
    for (const name of await readdir(previous))
      await rename(join(previous, name), join(current, name));
    await rm(previous, { recursive: true, force: true });
  }
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
